# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'starganv2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources

class Ui_formStarGANv2(object):
    def setupUi(self, formStarGANv2):
        formStarGANv2.setObjectName("formStarGANv2")
        formStarGANv2.resize(400, 536)
        self.gridLayout_2 = QtWidgets.QGridLayout(formStarGANv2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frameConfig = QtWidgets.QFrame(formStarGANv2)
        self.frameConfig.setStyleSheet("background-color: rgba(245, 245, 245, 200);")
        self.frameConfig.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameConfig.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameConfig.setObjectName("frameConfig")
        self.gridLayout = QtWidgets.QGridLayout(self.frameConfig)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.configLbl = QtWidgets.QLabel(self.frameConfig)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.configLbl.setFont(font)
        self.configLbl.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.configLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.configLbl.setObjectName("configLbl")
        self.gridLayout.addWidget(self.configLbl, 0, 0, 1, 1)
        self.dirBtn = QtWidgets.QPushButton(self.frameConfig)
        self.dirBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.dirBtn.setFont(font)
        self.dirBtn.setObjectName("dirBtn")
        self.gridLayout.addWidget(self.dirBtn, 1, 0, 1, 1)
        self.dirPth = QtWidgets.QLineEdit(self.frameConfig)
        self.dirPth.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.dirPth.setFont(font)
        self.dirPth.setObjectName("dirPth")
        self.gridLayout.addWidget(self.dirPth, 1, 1, 1, 1)
        self.deviceBtn = QtWidgets.QPushButton(self.frameConfig)
        self.deviceBtn.setMinimumSize(QtCore.QSize(100, 100))
        self.deviceBtn.setMaximumSize(QtCore.QSize(100, 100))
        self.deviceBtn.setStyleSheet("border-image: url(:/resources/common/gpu-off.png);")
        self.deviceBtn.setText("")
        self.deviceBtn.setObjectName("deviceBtn")
        self.gridLayout.addWidget(self.deviceBtn, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.loadBtn = QtWidgets.QPushButton(self.frameConfig)
        self.loadBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.loadBtn.setFont(font)
        self.loadBtn.setObjectName("loadBtn")
        self.gridLayout.addWidget(self.loadBtn, 2, 0, 1, 2)
        self.gridLayout_2.addWidget(self.frameConfig, 0, 0, 1, 1)

        self.retranslateUi(formStarGANv2)
        QtCore.QMetaObject.connectSlotsByName(formStarGANv2)

    def retranslateUi(self, formStarGANv2):
        _translate = QtCore.QCoreApplication.translate
        formStarGANv2.setWindowTitle(_translate("formStarGANv2", "formStarGANv2"))
        self.configLbl.setText(_translate("formStarGANv2", "StarGANv2"))
        self.dirBtn.setText(_translate("formStarGANv2", "model directory"))
        self.loadBtn.setText(_translate("formStarGANv2", "load model"))

